### ISSUE TITLE
Roadmap engilsh spelling remarks

### ISSUE THREAD

**Issue by salmer** [salmer/CppDeveloperRoadmap#29]
There's some Russian characters after "choose one of the popular IDEs"
* Occam is spelled with two 'C's, not two 'K's.
* Uint tests should be unit tests.
* Virualization -> virtualisation (whether you want * British or American English is up to you, but at least put the T there).

**Comment by skitleer** [comment]
standarts -> standards

**Comment by DmitrievDmitriyA** [comment]
@skitleer Fixed. Thank you!

**Comment by DmitrievDmitriyA** [comment]
Let's leave it open for now. In case if there are more typos

**Comment by StenBone** [comment]
Found a Russian word that hadn't been translated on Overview.md. I had already created the PR before seeing this issue. 
https://github.com/salmer/CppDeveloperRoadmap/pull/30
