### ISSUE TITLE
Предлагаю фигануть опенсорсный курс

### ISSUE THREAD

**Issue by mokevnin** [salmer/CppDeveloperRoadmap#3]
Ребят, у нас тут есть открытый проект https://ru.code-basics.com/ где дается база по кучке языков. Все это опенсорсное и у нас даже есть заготовка под cpp. Хотите поучаствовать? https://github.com/hexlet-basics/exercises-cpp

**Comment by Jihadist** [comment]
Лекции Владимирова из МФТИ (https://www.youtube.com/channel/UCvmBEbr9NZt7UEh9doI7n_A) в свободном доступе и на русском. Вряд ли выйдет лучше

**Comment by mokevnin** [comment]
На бейзиксе главное это практика и задача не в том чтобы научить языку, а в том чтобы им заинтересовать, чтобы человек мог прямо тут же в браузере попробовать что то простое сделать. Посмотрите например любой урок по джаве, практика там доступна без регистрации. Мы в любом случае это будем делать, просто я написал щас вам потому что кто то из ваших тегнул меня в твиттере с просьбой распостранить

**Comment by DmitrievDmitriyA** [comment]
@mokevnin привет, Кирилл, мы за вами следим и нам нравится хекслет :) 
У нас личные цели сейчас в другом направление устремлены, поэтому пока не готовы вписаться, но, судя по структуре проекта, к вам можно в любой момент подключиться помогать кейсы набрасывать.
Спасибо за предложение! 
Как с вами лучше связываться?

**Comment by mokevnin** [comment]
Давай в телеге, у меня там такой же ник. А так да, бейзикс опенсорсный и по самому проекту и по контенту который на нем, там многое делается нашим комьюнити. C++ нас просят, так что мы как-минимум лежим в эту сторону)

**Comment by DmitrievDmitriyA** [comment]
@mokevnin принял, спасибо!
