### ISSUE TITLE
Майндмэп. ОС --> Контейнеризация

### ISSUE THREAD

**Issue by saracen24** [salmer/CppDeveloperRoadmap#31]
В майндмэпе в ветке ОС упомянута виртуализация. Предлагаю добавить контейнеразцию.

**Comment by salmer** [comment]
@saracen24 Спасибо! Добавил ветку в следующем виде:

![image](https://user-images.githubusercontent.com/14817858/141653757-4d99838f-a1e9-4ab4-9905-2e40280bcb17.png)
![image](https://user-images.githubusercontent.com/14817858/141653770-6c7c1373-d530-463e-bf3f-475c522dbe75.png)
