### ISSUE TITLE
Create a topic with a list of YouTube videos related to C++ basics and common practices (cppcon, boostcon, etc.)

### ISSUE THREAD

**Issue by salmer** [salmer/CppDeveloperRoadmap#42]
It's nice to create a list of videos about common knowledge about C++ for juniors and middle developers. It's nice to have videos that explain the most useful technics and tricks in daily development: for example: 
* Jonathan Boccara - 105 STL Algorithms in Less Than an Hour
* Herb Sutter - Back to the Basics! Essentials of Modern C++ Style

**Comment by HappyBeer63** [comment]
https://youtube.com/playlist?list=PLQOaTSbfxUtCrKs0nicOg2npJQYSPGO9r

**Comment by SoulRiets** [comment]
https://www.youtube.com/watch?v=18c3MTX0PK0&list=PLlrATfBNZ98dudnM48yfGUldqGD0S4FFb

**Comment by FahimFBA** [comment]
Should I add them one by one here, or should I add them in a GitHub gist and share the link of the gist here?

**Comment by salmer** [comment]
this collection is available on the https://hackingcpp.com/index.html

no reason to reinvent it.
