### ISSUE TITLE
Which Stroustrup book(s) to avoid? Warning is ambiguous.

### ISSUE THREAD

**Issue by jamesakirk** [salmer/CppDeveloperRoadmap#63]
On [Learn C++ using the book by Stroustrup](https://salmer.github.io/CppDeveloperRoadmap/English/Mythbusters.html)

Which states:

> Learn C++ using the book by Stroustrup
> A highly damaging thesis taking origin from the “Old Guard” or someone born with a keyboard in hand.
> 
> Those who had extensive experience of development in other languages (C, Fortran, Delphi, etc.) and transitioned to C++ are most likely to give this piece of advice. Stroustrup wrote this book like a reference, therefore one needs to use it in the appropriate manner, which requires some knowledge of the language. Better look at the Books section, you’ll find books for any level of language proficiency.

What book are you referring to? BS has authored several books in the past few years including:

1. Programming -- Principles and Practice Using C++
2. A Tour of C++
3.  The C++ Programming Language

**Comment by salmer** [comment]
Hi @jamesakirk! Nice catch. Indeed this topic talks more about "The C++ Programming Language". This book is too hard for newbies and  it's better to look up for simplistic alternatives. I'll mention this book to make it explicit in this topic.

Thank you and happy new year!

**Comment by salmer** [comment]
It's fixed now.
