### ISSUE TITLE
Hello,  I was impressed by the repo. So  i want to translate to my language about Korean Could i do? ,sir?

### ISSUE THREAD

**Issue by Buppong** [salmer/CppDeveloperRoadmap#67]
**Describe the solution you'd like**

i try to translate that is it. :) 

thank u

**Comment by Buppong** [comment]
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> i try to translate that is it. :)
> 
> thank u

**Comment by salmer** [comment]
Hello @Buppong. 

We're really appreciate any input for the roadmap, especially translation to other languages. 

If you're ready to provide translations for all the articles to the content, you're welcome to do it.

I propose to follow the following agreements:
- I' will create a new folder "Korean" and all other nested folders in the root of the repository for the translation
- Keep the naming of the files in English to be able to have them synchronised and tracked for all the languages
- Put all the translated *.md files to the same folders as it's done for other languages
- Try to find equal books about C++ in Korean and provide links (alternatives for Amazon in Korea). If not - keep links to English versions of books.
- Translate the GraphML version of the roadmap and push it to master. When it's done I'll create a Miro board for Korean language and copy/paste all the translated leafs.
- Please keep all the links to other pages non absolute not to break forwarding to other pages
- Please create PRs when you're done with articles, I'll approve them and will merge to master.

Btw, we tend to maintain and update the roadmap from time to time: modify articles and add new books (remove old ones). Will you be able to help us with it in the future if new content is added?

Thank you for helping us to spread knowledge and roadmap for C++!

**Comment by salmer** [comment]
@Buppong the new folder is created for Korean with all the files in English: https://github.com/salmer/CppDeveloperRoadmap/pull/68. 

You can use it for the translation :-)
