### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by Alraun16** [salmer/CppDeveloperRoadmap#78]
Привет.
Видимо, это единственный способ связаться по поводу созданной Mind-карты по изучению С++, так что пишу здесь. Рассчитываю на ответ :)
Я новичок в С++. Можно сказать, знаю базу языка, общепредоставленные основы, одинаковые от сайта к сайту и от книги к книге. От типов данных до классов. 

Просмотрел всю вашу карту. Условно понятно, что чтобы быть разработчиком С++, надо понимать все перечисленные вещи. Даже указан порядок изучения. Однако совсем непонятно, а что собственно делать, что именно программировать, чтобы набираться опыта, какие задачи реализовывать на языке, чтобы осваивать навыки с mind-mapa. То есть на карте показано, ЧТО нужно знать, но не КАК это узнать, в каких ситуациях ЭТО нужно и нужно ли вообще. В целом-то не ясно даже, с чего начать.  

Вот, и я, как новичок, в небольшом тупике. Базу усвоил, с алгоритмами и алгеброй поигрался. И хочется как-то развиваться дальше, в последствии трудоустраиваться. А что пытаться программировать-то.... И как эта карта вообще может мне помочь.
Mind-карта составлена вроде как и для новичков, а вроде и совсем никак неопределённость не уменьшает. 
Может, будут какие-то общие советы, как использовать собранную карту с пользой? И как быть новоиспечённому зачатку программиста на С++? :(

**Comment by salmer** [comment]
Привет.

На вышеперечисленные вопросы мы попытались ответить в рамках представленного репозитория, который идет в качестве сопровождения к дорожной карте. 

Рекомендуем ознакомиться с нижеперечисленными статьями, они отвечают на заданные вопросы:
- Книги для изучения: https://github.com/salmer/CppDeveloperRoadmap/blob/main/Russian/Books/Overview.md
- Идеи пет-проектов: https://github.com/salmer/CppDeveloperRoadmap/blob/main/Russian/PetProjects.md
- Тулинг для работы на С++: https://github.com/salmer/CppDeveloperRoadmap/blob/main/Russian/Tooling.md
- Прочие источники изучения: https://github.com/salmer/CppDeveloperRoadmap/blob/main/Russian/CommunitySources.md

В целом, общая рекомендация может быть следующей: идти по литературе, из раздела "Книги", которая касается C++: от уровня джуниора и до синьора. В целом, если нужно супер быстро прокачаться базово в языке, то очень рекомендуем начать с книг Скотта Майерса, а затем Герба Саттера. Они содержат достаточный объем релевантной информации, которые дадут уверенный фундамент по С++, а также примеры популярных идиом/паттернов, которые встречаются в 95% коммерческих проектов. Дальше уже можно будет читать то, что кажется интересным или необходимым на практике.

Из новых источников также очень рекомендую:
- Онлайн учебник (только на английском): https://learncpp.com
- Сборник шпаргалок, записи по C++ с офлайн концеренций, набор книг и т.д.: https://hackingcpp.com

Идеи пет-проектов: мы тоже постарались накидать некое количество примеров, в качестве отправной точки. Но дальше только полет собственной фантазии может помочь, ибо сложно предсказать, какого рода приложения для разработки конкретно интересны вам.

Спасибо за отзыв на дорожную карту, очень хорошее подмечено замечание, что нету никаких "якорей", отсылающих к ресурсам, которые раскрывают тот или аспект языка. 

У нас была подобная идея для реализации, но пока что она выглядит слишком грандиозной для автономной реализации "с нуля". Но прокинуть какие-либо либо ссылки на иные ресурсы кажется вполне реальной задачей, мы подумаем над подобной доработкой. :) 

Если есть дополнительные вопросы, то задавайте их здесь.

**Comment by Alraun16** [comment]
Спасибо за развёрнутый ответ.
Постараюсь в ближайшем будущем дать информативный фидбек по этим советам и майнд-карте в процессе дальнейшего изучения С++. Правда не хватало подобной собранной в одном месте информации - её поиск в десятке разных источников малость убивает энтузиазм и интерес к освоению языка, тем более не самого дружелюбного на порог вхождения.
