### ISSUE TITLE
Демонстрационные примеры

### ISSUE THREAD

**Issue by d7d1cd** [salmer/CppDeveloperRoadmap#79]
Добрый день. Предлагаю для каждого "дорожного пункта", где это возможно, добавить ссылку на godbolt, где будет приведен демонстрационный пример. Например, человек открывает карту, идет по пунктам Hard skills - Синтаксис языка - Базовые операции - Циклы for/while, щелкает на последний пункт и видит примеры живого применения циклов с комментариями.
Так же можно добавить ссылки на статьи по теме "дорожного пункта".

**Comment by salmer** [comment]
Добрый день! Спасибо за предложение, идея звучит отлично, это действительно может быть очень полезным - иметь пример кода на ветви того или иного пункта дорожной карты.

Я подумаю над тем, каким образом это можно органично вплести в дорожную карту, чтобы не перегрузить ее, но при этом сделать интуитивно понятным :)

Если есть ещё какие предложения, всегда рады услышать про них.

Хорошего вам дня!

**Comment by d7d1cd** [comment]
Может сделать сам пункт дорожной карты ссылкой на godbolt?

**Comment by lma10h** [comment]
А я бы отказался от такой опции, пусть терминальная точка карты будет как функция, а ее реализация это уже "зависит от", как говорится:) Подойдут и курсы и книги и статьи, тем более на каждую такую тему их полным полно.

Up to you конечно, мейнтейнер, но противоположная точка зрения может быть тоже полезна:)
