### ISSUE TITLE
Плейлист Ильи Мещерина удален

### ISSUE THREAD

**Issue by station437** [salmer/CppDeveloperRoadmap#80]
https://github.com/salmer/CppDeveloperRoadmap/blob/ec4a78f72cc86ffafc4bae94d9e5bbfc6794e357/Russian/Books/PreJunior.md?plain=1#L38

может этот плейлист?
https://www.youtube.com/playlist?list=PLmSYEYYGhnBu1fFtnzKx-pycYbJnb0rOl

**Comment by salmer** [comment]
@station437, спасибо, что нашли битую ссылку. Поправлю, да - это то что там раньше было. Видимо Илья обновил плейлист.
