### ISSUE TITLE
Этап "Алгоритмы и структуры данных"

### ISSUE THREAD

**Issue by lma10h** [salmer/CppDeveloperRoadmap#93]
Добрый день, предлагаю подсказать "как измерить" знания по алгоритмам и структурам данных. Например, указать на ваш взгляд примерное кол-во решенных задач на leetcode.com (для junior/middle/senior свои числа), или рэндж по цветам codeforces.com (например, junior это серый-фиолетовый и тп)

Надеюсь, это поможет адекватно и прозрачно оценивать начинающим свои силы, что от них ждут на собесе:)

**Comment by DmitrievDmitriyA** [comment]
@lma10h добрый день,

проблема в том, что в разные компании и на разные позиции ожидают разный уровень владения алгоритмами и структурами данных. К тому же это не некая постоянная величина - рынок постоянно изменяется, поэтому очень сложно дать какой-то средний совет по больнице. К тому же каждый начинает чувствовать собственную уверенность после разного количества решённых задач, поэтому мы предпочли оставить это на усмотрение тех, кто только постигает язык ;)

Спасибо за идею! Мы ценим.
