### ISSUE TITLE
update markdown link

### ISSUE THREAD

**Issue by urasssopretty** [salmer/CppDeveloperRoadmap#94]
in the Russian version on the Mythbusters.md page, the link to the book file should be updated in the section "Изучайте С++ только по стандарту"

now the link leads to https://github.com/salmer/CppDeveloperRoadmap/blob/main/Russian/Books.md
but should lead to https://github.com/salmer/CppDeveloperRoadmap/blob/main/Russian/Books/Overview.md

**Comment by DmitrievDmitriyA** [comment]
@urasssopretty  Огонь! Спасибо 👍
