### ISSUE TITLE
What is the correct order?

### ISSUE THREAD

**Issue by Cristian-Alvarez29** [salmer/CppDeveloperRoadmap#98]
I have reviewed the route but, on the right side (hard skill) there are sections separated by steps, I cannot understand the correct order. In principle there are 4 very clear steps, then 1, 3, 5 Then 1, 4 and 2. **I'm confused** 😮‍💨

![image](https://github.com/user-attachments/assets/df045f97-9968-4710-b05e-b267b08fcefe)

**Comment by SRX-YT** [comment]
up to down will be correct
